### ISSUE TITLE
PlotHeatMap.m

### ISSUE THREAD

**Issue by Qiaohhh** [Future-Power-Networks/Simplus-Grid-Tool#35]
Thank you for sharing. I found an error while running this program.

In the **60th line** of the function **PlotHeatMap. m**, the function **clim** is not defined. I think you want to use the function **zlim**, but after changing **clim** to **zlim**, the heatmap is not displayed. Therefore, I suggest **commenting out lines 55 to 60 of the code**.

**Comment by yt-li** [comment]
Thanks for raising this issue. The function "clim" is only available for Matlab version 2021 or later. The corresponding lines are commented out as you suggested, so that the users with older Matlab version can also use the toolbox. Many thanks!
