### ISSUE TITLE
Errors in code of PlotLayoutGraph

### ISSUE THREAD

**Issue by MoryNajafi** [Future-Power-Networks/Simplus-Grid-Tool#36]
Running the toolbox in lower versions of MATLAB, e.g. R2018, there are two errors:

"Error using matlab.graphics.chart.primitive.GraphPlot/highlight>checkEdgesNodePair
s and t must both be numeric indices or both be cell arrays of character vectors."
"Error in matlab.graphics.chart.primitive.GraphPlot/highlight"

These errors relate to PlotLayoutGraph.m, lines 18 and 19. The code is available in Simplus-Grid-Tool-master\+SimplusGT\+Toolbox.
line 18: highlight(Figure,Data,'NodeFontSize',9);
line 19: highlight(Figure,Data,'NodeFontWeight','bold');

The causes for these errors are that in lower MATLAB versions, NodeFontSize and NodeFontWeigth are not available for the highlight() function.

So, by removing those options in lines 18 and 19, the errors disappear.

**Comment by yt-li** [comment]
Thanks for observing these.
