### ISSUE TITLE
v2024-Aug-19 版本在mac的matlab中运行会报错

### ISSUE THREAD

**Issue by moonglaivecn** [Future-Power-Networks/Simplus-Grid-Tool#39]
Usermain.m中使用
UserDataName = 'IEEE_14Bus';
运行后出现

、、、    
    出错 SimplusGT.Toolbox.Excel2Json (第 38 行)
        ExcelBasic = xlsread(ExcelFile,'Basic');
    
    出错 SimplusGT.Toolbox.Main (第 29 行)
        SimplusGT.Toolbox.Excel2Json(UserData);
    
    出错 UserMain (第 45 行)
    SimplusGT.Toolbox.Main();
、、、

原因是Excel2Json.m文件中
、、、
ExcelFile = [FolderName,'\',FileName];
、、、

识别的路径会变成....AcPowerSystem/IEEE_14Bus\IEEE_14Bus.xlsx，在mac中无法识别，将上述代码修改后运行成功。
、、、
ExcelFile = [FolderName,'/‘,FileName];
、、、

修改后不影响windows操作系统中代码的运行。如运行有问题，请保持,'/'一致
、、
    if strcmp(ExcelFile(1),'/')
        ExcelFile = ExcelFile(2:end);
    end
、、、

**Comment by yt-li** [comment]
Thanks for your very kind suggestion. We solved it.
